### ISSUE TITLE
cannot find attack_csgld_pgd_torch.py

### ISSUE THREAD

**Issue by zhengmeixi** [Framartin/lgv-geometric-transferability#1]
Thanks for your amazing work and detailed repo. But I cannot find the attack file **attack_csgld_pgd_torch.py**. I'm not sure whether I missed something. Could you please tell me where I can find it? Thanks!

**Comment by Framartin** [comment]
Hello @zhengmeixi ,
Thank you for your interest in my work and for spotting this. I forgot to add this file! This should be fixed with eb024bd 
If you want to simply want to use LGV, without all the experiments of the paper, I recommend to use the refactored implementation merged in the `torchattacks` library: https://adversarial-attacks-pytorch.readthedocs.io/en/latest/wrappers.html#module-torchattacks.wrappers.lgv  
Anyway, feel free to reach out if you have any doubt on this code base.
Best.

**Comment by zhengmeixi** [comment]
Hi,
Thanks for your answer :) I do hava another question. In func **ExtendedProjectedGradientDescentPyTorch** in utils/attacks.py, **self._compute_torch** is used to generate adversarial images, but it seems that this func is not degfined.

**Comment by Framartin** [comment]
The `_compute_torch()` method of `ExtendedProjectedGradientDescentPyTorch` should be inherited from its parent class `ProjectedGradientDescentPyTorch` of the ART library. Did you install `adversarial-robustness-toolbox`? I used it in its 1.6.0 version. A later version of ART may have refactored `ProjectedGradientDescentPyTorch._compute_torch()`. Please let me know if it does not work.
